/ *
1. CREAR UNA FUNCION QUE MUESTRE EL HISTORICO DE
   COMPRA DE CADA CLIENTE
   CLIENTE | PRODUCTO | MONTO COMPRADO
2. FUNCION QUE MUESTRE EL MONTO TOTAL COMPRADO POR
   CADA CLIENTE ORDENANDOLO DE MAYOR A MENOR
   CLIENTE | MONTO COMPRADO
3. MOSTRAR LOS PRODUCTOS MAS COMPRADOS MAYORES A 
   3500 SOLES DE COMPRA
   PRODUCTO | MONTO COMPRADO
* /
